// Email service for sending transactional emails
// Supports SendGrid and Resend integrations via environment variables

export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  from?: string;
}

export async function sendEmail(options: EmailOptions): Promise<boolean> {
  const { to, subject, html, from = "hello@theheartNextdoor.com" } = options;

  try {
    // Check which email service is configured
    const sendgridKey = process.env.SENDGRID_API_KEY;
    const resendKey = process.env.RESEND_API_KEY;

    if (sendgridKey) {
      return await sendViaSendGrid({ to, subject, html, from });
    } else if (resendKey) {
      return await sendViaResend({ to, subject, html, from });
    } else {
      console.warn("No email service configured (SENDGRID_API_KEY or RESEND_API_KEY)");
      return false;
    }
  } catch (error) {
    console.error("Email sending error:", error);
    return false;
  }
}

async function sendViaSendGrid(options: EmailOptions): Promise<boolean> {
  try {
    const response = await fetch("https://api.sendgrid.com/v3/mail/send", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${process.env.SENDGRID_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        personalizations: [
          {
            to: [{ email: options.to }],
            subject: options.subject,
          },
        ],
        from: { email: options.from },
        content: [
          {
            type: "text/html",
            value: options.html,
          },
        ],
      }),
    });

    return response.ok;
  } catch (error) {
    console.error("SendGrid error:", error);
    return false;
  }
}

async function sendViaResend(options: EmailOptions): Promise<boolean> {
  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${process.env.RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: options.from,
        to: options.to,
        subject: options.subject,
        html: options.html,
      }),
    });

    return response.ok;
  } catch (error) {
    console.error("Resend error:", error);
    return false;
  }
}

export async function sendRedFlagAlert(options: {
  motherName: string;
  providerEmail: string;
  providerName: string;
  alert: string;
  details: string;
}): Promise<boolean> {
  const html = `
    <h2>🚨 Maternal Health Alert for ${options.motherName}</h2>
    <p><strong>Alert:</strong> ${options.alert}</p>
    <p><strong>Details:</strong> ${options.details}</p>
    <p style="color: #666; font-size: 12px; margin-top: 20px;">
      This alert was generated by The Heart Next Door maternal wellness app based on daily check-in data.
      Please follow up with the patient directly to assess their current situation.
    </p>
  `;

  return sendEmail({
    to: options.providerEmail,
    subject: `🚨 Maternal Health Alert: ${options.motherName}`,
    html,
  });
}

export async function sendNotificationEmail(options: {
  recipientEmail: string;
  recipientName: string;
  title: string;
  message: string;
}): Promise<boolean> {
  const html = `
    <p>Hi ${options.recipientName},</p>
    <p><strong>${options.title}</strong></p>
    <p>${options.message}</p>
    <p style="color: #666; font-size: 12px; margin-top: 20px;">
      — The Heart Next Door
    </p>
  `;

  return sendEmail({
    to: options.recipientEmail,
    subject: options.title,
    html,
  });
}
